config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shelter.urls", namespace="shelter")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

shelter/urls.py
from django.urls import path, include

from shelter.views import (
    IndexView,
    AdoptPet,
    BreedListView,
    BreedCreateView,
    BreedUpdateView,
    CatListView,
    CatCreateView,
    CatUpdateView,
    DogListView,
    DogCreateView,
    DogUpdateView,
    PetDetailView,
    PetListView,
    PetOwnerListView,
    PetOwnerCreateView,
    PetOwnerDetailView,
    PetOwnerUpdateView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "breeds/create/",
        BreedCreateView.as_view(),
        name="breed-create"
    ),
    path(
        "breeds/<int:pk>/update/",
        BreedUpdateView.as_view(),
        name="breed-update"
    ),
    path(
        "breeds/",
        BreedListView.as_view(),
        name="breed-list"
    ),
    path(
        "dogs/",
        DogListView.as_view(),
        name="dog-list"
    ),
    path(
        "dogs/create/",
        DogCreateView.as_view(),
        name="dog-create"
    ),
    path(
        "dogs/<int:pk>/update/",
        DogUpdateView.as_view(),
        name="dog-update"
    ),
    path(
        "cats/",
        CatListView.as_view(),
        name="cat-list"
    ),
    path(
        "cats/create/",
        CatCreateView.as_view(),
        name="cat-create"
    ),
    path(
        "cats/<int:pk>/update/",
        CatUpdateView.as_view(),
        name="cat-update"
    ),
    path(
        "pets/<int:pk>/detail/",
        PetDetailView.as_view(),
        name="pet-detail"
    ),
    path(
        "pets/",
        PetListView.as_view(),
        name="pet-list"
    ),
    path(
        "users/",
        PetOwnerListView.as_view(),
        name="pet-owner-list"
    ),
    path(
        "users/create/",
        PetOwnerCreateView.as_view(),
        name="pet-owner-create"
    ),
    path(
        "pets/<int:pk>/adopt/",
        AdoptPet.as_view(),
        name="adopt-pet"
    ),
    path(
        "users/<int:pk>/detail/",
        PetOwnerDetailView.as_view(),
        name="pet-owner-detail"
    ),
    path(
        "users/<int:pk>/update/",
        PetOwnerUpdateView.as_view(),
        name="pet-owner-update"
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

app_name = "shelter"

shelter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from shelter.models import Pet, Breed, PetOwner, Type


class BreedSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    type = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )


class CatForm(forms.ModelForm):
    breed = forms.ModelChoiceField(
        queryset=Breed.objects.filter(type__name="Cat"),
        required=False
    )
    type = forms.ModelChoiceField(
        queryset=Type.objects.filter(name="Cat"),
    )

    class Meta:
        model = Pet
        exclude = ("pet_owner", "left_at")


class CatSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    breed = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    gender = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )


class DogForm(forms.ModelForm):
    breed = forms.ModelChoiceField(
        queryset=Breed.objects.filter(type__name="Dog"),
        required=False
    )
    type = forms.ModelChoiceField(
        queryset=Type.objects.filter(name="Dog"),
    )

    class Meta:
        model = Pet
        exclude = ("pet_owner", "left_at")


class DogSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    breed = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    gender = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )


class PetSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    breed = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    gender = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )


class PetOwnerCreationForm(UserCreationForm):
    class Meta:
        model = PetOwner
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "phone_number"
        )


class PetOwnerUpdateForm(forms.ModelForm):
    class Meta:
        model = PetOwner
        fields = ("email", "phone_number")


class PetOwnerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )
    first_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput()
    )

shelter/views.py
from datetime import date

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import AccessMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic, View

from shelter.forms import (
    BreedSearchForm,
    CatForm,
    DogForm,
    PetOwnerCreationForm,
    PetOwnerUpdateForm,
    CatSearchForm,
    DogSearchForm,
    PetSearchForm,
    PetOwnerSearchForm,
)
from shelter.models import Breed, Pet, PetOwner, Type


class IndexView(View):

    @staticmethod
    def get(request):
        Type.objects.get_or_create(name="Dog")
        Type.objects.get_or_create(name="Cat")

        num_shelter_cats = Pet.objects.filter(
            type__name="Cat", left_at=None
        ).count()
        num_shelter_dogs = Pet.objects.filter(
            type__name="Dog", left_at__isnull=True
        ).count()
        num_home_dogs = Pet.objects.filter(
            type__name="Dog", left_at__isnull=False
        ).count()
        num_home_cats = Pet.objects.filter(
            type__name="Cat", left_at__isnull=False
        ).count()

        context = {
            "num_shelter_cats": num_shelter_cats,
            "num_shelter_dogs": num_shelter_dogs,
            "num_home_dogs": num_home_dogs,
            "num_home_cats": num_home_cats
        }
        return render(request, "shelter/index.html", context=context)


class StaffUserRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            if self.raise_exception:
                raise PermissionDenied
            else:
                return redirect(reverse("shelter:index"))

        return super(StaffUserRequiredMixin, self).dispatch(
            request, *args, **kwargs
        )


class RightUserRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.id != kwargs["pk"] and not request.user.is_staff:
            if self.raise_exception:
                raise PermissionDenied
            else:
                return redirect(reverse("shelter:index"))

        return super(RightUserRequiredMixin, self).dispatch(
            request, *args, **kwargs
        )


class AdoptPet(StaffUserRequiredMixin, View):

    @staticmethod
    def post(request, pk):
        pet = get_object_or_404(Pet, pk=pk)
        username = request.POST.get("username")
        pet_owner = get_user_model().objects.get(username=username)

        if pet in pet_owner.pets.all():
            pet.left_at = None
            pet.save()
            pet_owner.pets.remove(pet)
        else:
            pet.left_at = date.today()
            pet.save()
            pet_owner.pets.add(pet)
        pet_owner.save()

        return redirect('shelter:pet-detail', pk=pet.id)


class BreedListView(generic.ListView):
    model = Breed
    context_object_name = "breed_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BreedListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        type_ = self.request.GET.get("type", "")

        if name:
            context["search_form"] = BreedSearchForm(initial={
                "name": name,
            })
        if type_:
            context["search_form"] = BreedSearchForm(initial={
                "type": type_,
            })

        return context

    def get_queryset(self):
        form = BreedSearchForm(self.request.GET)
        queryset = Breed.objects.select_related("type")

        form.is_valid()

        if form.cleaned_data["name"]:
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        elif form.cleaned_data["type"]:
            return queryset.filter(
                type__name__icontains=form.cleaned_data["type"]
            )

        return queryset


class BreedCreateView(StaffUserRequiredMixin, generic.CreateView):
    model = Breed
    fields = "__all__"
    template_name = "shelter/breed_form.html"
    success_url = reverse_lazy("shelter:breed-list")


class BreedUpdateView(StaffUserRequiredMixin, generic.UpdateView):
    model = Breed
    fields = "__all__"
    template_name = "shelter/breed_form.html"
    success_url = reverse_lazy("shelter:breed-list")


class CatListView(generic.ListView):
    model = Pet
    template_name = "shelter/cat_list.html"
    context_object_name = "cat_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CatListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        breed = self.request.GET.get("breed", "")
        gender = self.request.GET.get("gender", "")

        if name:
            context["search_form"] = CatSearchForm(initial={
                "name": name,
            })
        elif breed:
            context["search_form"] = CatSearchForm(initial={
                "breed": breed,
            })
        elif gender:
            context["search_form"] = CatSearchForm(initial={
                "gender": gender,
            })

        return context

    def get_queryset(self):
        form = CatSearchForm(self.request.GET)
        queryset = Pet.objects.filter(
            type__name="Cat", left_at__isnull=True
        ).order_by("arrived_at")

        form.is_valid()

        if form.cleaned_data["name"]:
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        elif form.cleaned_data["breed"]:
            return queryset.filter(
                breed__name__icontains=form.cleaned_data["breed"]
            )
        elif form.cleaned_data["gender"]:
            return queryset.filter(
                gender__icontains=form.cleaned_data["gender"]
            )

        return queryset


class CatCreateView(StaffUserRequiredMixin, generic.CreateView):
    form_class = CatForm
    template_name = "shelter/cat_form.html"
    success_url = reverse_lazy("shelter:cat-list")


class CatUpdateView(StaffUserRequiredMixin, generic.UpdateView):
    model = Pet
    form_class = CatForm
    template_name = "shelter/cat_form.html"
    success_url = reverse_lazy("shelter:cat-list")


class DogListView(generic.ListView):
    model = Pet
    template_name = "shelter/dog_list.html"
    context_object_name = "dog_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DogListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        breed = self.request.GET.get("breed", "")
        gender = self.request.GET.get("gender", "")

        if name:
            context["search_form"] = CatSearchForm(initial={
                "name": name,
            })
        elif breed:
            context["search_form"] = CatSearchForm(initial={
                "breed": breed,
            })
        elif gender:
            context["search_form"] = CatSearchForm(initial={
                "gender": gender,
            })

        return context

    def get_queryset(self):
        form = DogSearchForm(self.request.GET)

        queryset = Pet.objects.filter(
            type__name="Dog", left_at__isnull=True
        ).order_by("arrived_at")

        form.is_valid()

        if form.cleaned_data["name"]:
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        elif form.cleaned_data["breed"]:
            return queryset.filter(
                breed__name__icontains=form.cleaned_data["breed"]
            )
        elif form.cleaned_data["gender"]:
            return queryset.filter(
                gender__icontains=form.cleaned_data["gender"]
            )

        return queryset


class DogCreateView(StaffUserRequiredMixin, generic.CreateView):
    form_class = DogForm
    template_name = "shelter/dog_form.html"
    success_url = reverse_lazy("shelter:dog-list")


class DogUpdateView(StaffUserRequiredMixin, generic.UpdateView):
    model = Pet
    form_class = DogForm
    template_name = "shelter/dog_form.html"
    success_url = reverse_lazy("shelter:dog-list")


class PetDetailView(generic.DetailView):
    model = Pet
    template_name = "shelter/pet_detail.html"
    context_object_name = "pet_detail"
    queryset = Pet.objects.select_related("type", "breed", "pet_owner")


class PetListView(StaffUserRequiredMixin, generic.ListView):
    model = Pet
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PetListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        breed = self.request.GET.get("breed", "")
        gender = self.request.GET.get("gender", "")

        if name:
            context["search_form"] = PetSearchForm(initial={
                "name": name,
            })
        elif breed:
            context["search_form"] = PetSearchForm(initial={
                "breed": breed,
            })
        elif gender:
            context["search_form"] = PetSearchForm(initial={
                "gender": gender,
            })

        return context

    def get_queryset(self):
        form = PetSearchForm(self.request.GET)
        queryset = Pet.objects.select_related(
            "type", "breed"
        ).order_by("arrived_at")

        form.is_valid()

        if form.cleaned_data["name"]:
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]

templates/shelter/breed_form.html
{% extends "base.html" %}

{% block title %}
   <title>
     {{ object|yesno:"Update, Add" }} Breed | Pet Shelter
   </title>
{% endblock %}

{% block content %}
  <div class="w3-display-container height-400">
    <div class="w3-card-4 w3-margin w3-round-xxlarge w3-half w3-display-topmiddle">
      <div class="w3-container w3-black w3-round-xxlarge">
        <h2 class="w3-text-yellow w3-center">
          {{ object|yesno:"Update, Add" }} Breed
        </h2>
      </div>

      <form
          class="w3-container w3-padding"
          method="post"
          action="{% if object %} {% url 'shelter:breed-update' pk=object.id %}
                  {% else %} {% url 'shelter:breed-create' %} {% endif %}"
      >
        {% csrf_token %}
        <p>
          <label
              for="name"
              class="w3-text-black w3-padding"
          >
            <b>Name: *</b>
          </label>
          <input
              id="name"
              class="w3-input w3-border w3-sand w3-round-xxlarge w3-padding"
              name="name"
              type="text" {% if object %} value="{{ object.name }}" {% endif %}
              required
          >
          {% if form.errors.name %}
            {{ form.errors.name }}
          {% endif %}
        </p>
        <p>
          <label
              for="type"
              class="w3-text-black w3-padding"
          >
            <b>Type: *</b>
          </label>
          <select
              id="type"
              class="w3-select w3-border w3-sand w3-round-xxlarge w3-padding"
              name="type"
          >
            <option value="" disabled selected>
              Choose type
            </option>
            {% if form.type %}
              {% for type in form.type %}
                <option value="type">{{ type }}</option>
              {% endfor %}
            {% endif %}
          </select>
          {% if form.errors.type %}
            {{ form.errors.type }}
          {% endif %}
        </p>
        <p class="w3-center">
          <br>
          <button
              class="w3-btn w3-black w3-text-yellow w3-round-xxlarge"
              type="submit"
          >
            <b>Submit</b>
          </button>
        </p>
      </form>
    </div>
  </div>
{% endblock %}

templates/shelter/breed_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Breed List | Pet Shelter</title>
{% endblock %}

{% block content %}

  <div class="w3-container">
    <div class="w3-container w3-black w3-round-xxlarge list-title">
      <h2 class="w3-text-yellow w3-center">
        Breed List
      </h2>
    </div>
    {% if breed_list %}
      <div class="w3-row">
        <form
            action=""
            method="get"
            class="w3-half w3-padding"
        >
          <p class="w3-row w3-center">
            <input
                class="w3-input w3-border w3-sand
                       w3-round-xxlarge w3-center w3-margin"
                name="name"
                type="search"
                placeholder="Search by name"
                value="{{ search_form.name.value }}"
            />
          </p>
        </form>
        <form
            action=""
            method="get"
            class="w3-half w3-padding"
        >
          <p class="w3-row w3-center">
            <input
                class="w3-input w3-border w3-sand
                       w3-round-xxlarge w3-center w3-margin"
                name="type"
                type="search"
                placeholder="Search by type"
                value="{{ search_form.type.name.value }}"
            />
          </p>
        </form>
      </div>

      <table id="Table" class="w3-table w3-centered">
        <tr>
          <th class="width-30">
            Name
          </th>
          <th class="width-30">
            Type
          </th>
          <th class="width-30">
            Update
          </th>
        </tr>
        {% for breed in breed_list %}
          <tr>
            <td>
              <b>{{ breed.name }}</b>
            </td>
            <td>
              {{ breed.type.name }}
            </td>
            <td>
              <a href="{% url 'shelter:breed-update' pk=breed.id %}">
                UPDATE
              </a>
            </td>

          </tr>
        {% endfor %}
      </table>

    {% else %}
        <div class="w3-container w3-center">
        <br>
        <hr>
        <h2 class="w3-center">
          No breeds have been found
        </h2>
        <hr>
        <br>
        <p class="w3-center">
          <a
              href="{% url 'shelter:breed-list' %}"
              class="w3-btn w3-black w3-text-yellow
                     w3-round-xxlarge w3-xlarge"
          >
          Return back
          </a>
        </p>
      </div>
    {% endif %}

  </div>

{% endblock %}

templates/shelter/cat_form.html
{% extends "base.html" %}

{% block title %}
   <title>
     {{ object|yesno:"Update, Create" }} Profile | Pet Shelter
   </title>
{% endblock %}

{% block content %}
  <div class="w3-display-container pet-form-height">
    <div class="w3-card-4 w3-margin w3-round-xxlarge w3-half w3-display-topmiddle">
      <div class="w3-container w3-black w3-round-xxlarge">
        <h2 class="w3-text-yellow w3-center">
          {{ object|yesno:"Update, Create" }} Cat Profile
        </h2>
      </div>
      <form
          class="w3-container w3-padding"
          method="post"
          action="{% if object %} {% url 'shelter:cat-update' pk=object.id %}
                  {% else %} {% url 'shelter:cat-create' %}{% endif %}"
          enctype="multipart/form-data"
      >
        {% csrf_token %}
        <p>
          <label
              for="name"
              class="w3-text-black w3-padding">
            <b>Name: *</b>
          </label>
          <input
              id="name"
              class="w3-input w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="name"
              type="text"
              {% if object %} value="{{ object.name }}" {% endif %}
              required
          >
          {% if form.errors.name %}
            {{ form.errors.name }}
          {% endif %}
        </p>
        <div>
          <label class="w3-text-black w3-padding">
            <b>Gender: *</b>
          </label>
          <div class="w3-row w3-center">
            <div class="w3-half">
              <label>
                <input
                    class="w3-radio"
                    type="radio"
                    name="gender"
                    value="Male"
                    {% if object.gender == "Male" %} checked {% endif %}
                >
                Male
              </label>
            </div>
            <div class="w3-half">
              <label>
                <input
                    class="w3-radio"
                    type="radio"
                    name="gender"
                    value="Female"
                    {% if object.gender == "Female" %} checked {% endif %}
                    {% if not object %} checked {% endif %}
                    required
                >
                Female
              </label>
            </div>
          </div>
          {% if form.errors.gender %}
            {{ form.errors.gender }}
          {% endif %}
        </div>
        <p>
          <label
              for="type"
              class="w3-text-black w3-padding"
          >
            <b>Type: *</b>
          </label>
          <select
              id="type"
              class="w3-select w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="type"
          >
            <option value="" disabled selected>
              Choose type
            </option>
            {% if form.type %}
              {% for type in form.type %}
                <option value="type">{{ type }}</option>
              {% endfor %}
            {% endif %}
          </select>
          {% if form.errors.type %}
            {{ form.errors.type }}
          {% endif %}
        </p>
        <p>
          <label
              for="breed"
              class="w3-text-black w3-padding"
          >
            <b>Breed:</b>
          </label>
          <select
              id="breed"
              class="w3-select w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="breed"
          >
            <option value="" disabled selected>
              Choose breed
            </option>
            {% if form.breed %}
              {% for breed in form.breed %}
                <option value="breed">{{ breed }}</option>
              {% endfor %}
            {% endif %}
          </select>
          {% if form.errors.breed %}
            {{ form.errors.breed }}
          {% endif %}
        </p>
        <p>
          <label
              for="age"
              class="w3-text-black w3-padding"
          >
            <b>Age:</b>
          </label>
          <input
              id="age"
              class="w3-input w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="age"
              type="number"
              {% if object %} value="{{ object.age }}"
              {% else %} value="0" {% endif %}
          >
          {% if form.errors.age %}
            {{ form.errors.age }}
          {% endif %}
        </p>
        <p>
          <label
              for="description"
              class="w3-text-black w3-padding"
          >
            <b>Description:</b>
          </label>
          <textarea
              id="description"
              class="w3-input w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="description"
              rows="5"
              cols="40"
          >
            {% if object %} {{ object.description }} {% endif %}
          </textarea>
          {% if form.errors.description %}
            {{ form.errors.description }}
          {% endif %}
        </p>

        <p>
          <label
              for="photo"
              class="w3-text-black w3-padding">
            <b>Photo: </b>
          </label>
          <input
              id="photo"
              class="w3-input w3-border w3-sand
                     w3-round-xxlarge w3-padding"
              name="photo"
              type="url"
              {% if object %} value="{{ object.photo }}" {% endif %}
          >
          {% if form.errors.photo %}
            {{ form.errors.photo }}
          {% endif %}
        </p>
        <p class="w3-center">
          <br>
          <button
              class="w3-btn w3-black
                     w3-text-yellow w3-round-xxlarge"
              type="submit"
          >
            <b>Submit</b>
          </button>
        </p>
        </form>
    </div>
  </div>
{% endblock %}

templates/shelter/pet_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Pet Profile | Pet Shelter</title>
{% endblock %}

{% block content %}

  <div class="w3-row-padding">

    <div class="w3-third w3-padding-16">

      <div class="w3-white w3-text-grey w3-card-4 w3-round-xxlarge">
        <div class="w3-display-container">
          {% if pet_detail.photo %}
            <img
                src="{{pet_detail.photo}}"
                class="w3-round-xxlarge width-100"
                alt="Pet Photo"
            >
          {% else %}
            <img
                src="{% static 'images/coming_soon.png' %}"
                class="w3-round-xxlarge width-100"
                alt="Come Soon"
            >
          {% endif %}
        </div>
      </div>
      <br>

    </div>

    <div class="w3-twothird">
      <div class="w3-container w3-card w3-white w3-margin w3-round-xxlarge">
        <h2 class="w3-padding-16">
          <b>{{ pet_detail.name }}</b>
        </h2>
        {% if user.is_staff %}
          <button
              class="w3-btn w3-black w3-text-yellow w3-round-xxlarge"
              onclick="openAdoptionForm('Button')"
          >
            {% if pet_detail.pet_owner %}
              Abandon from the pet :(
            {% else %}
              Adopt the pet :)
            {% endif %}
          </button>
        {% endif %}

        <div
            id="Button"
            class="w3-hide w3-container w3-white w3-margin"
        >
          <form
              action="{% url 'shelter:adopt-pet' pk=object.id %}"
              method="post"
          >
            {% csrf_token %}
            <label
                for="username"
                class="w3-padding"
            >
              Pet's owner username:
            </label>
            <input
                id="username"
                type="text"
                name="username"
                class="w3-input w3-border w3-sand
                       w3-round-xxlarge width-30 w3-padding"
            >
            <br>
            <button
                class="w3-btn w3-black w3-text-yellow w3-round-xxlarge"
                type="submit">
              <b>Submit</b>
            </button>
          </form>
        </div>

        <div class="w3-container">
          <h6 class="w3-padding-16">
            <i class="fa fa-calendar fa-fw w3-margin-right"></i>
            {{ pet_detail.arrived_at }} -
            {% if not pet_detail.left_at %}
              <span class="w3-tag w3-round">Current</span>
            {% else %}
              {{ pet_detail.left_at }}
            {% endif %}
          </h6>
          <h5><b>Type:</b> {{ pet_detail.type }}</h5>
          <h5>
            <b>Breed:</b>
            {% if pet_detail.breed.name %}
              {{ pet_detail.breed.name }}
            {% else %}
              Unknown
            {% endif %}
          </h5>
          <hr>
        </div>
        <div class="w3-container">
          <h5><b>Gender:</b> {{ pet_detail.gender }}</h5>
          <h5>
            <b>Age:</b>
            {% if pet_detail.age %}
              {{ pet_detail.age }} year{{ pet_detail.age|pluralize }}
            {% else %}
              Unknown
            {% endif %}
          </h5>
          <hr>
        </div>
        {% if pet_detail.pet_owner %}
          <div class="w3-container">
            <h5><b>Pet Owner:</b>
              <a
                href="{% url 'shelter:pet-owner-detail' pk=pet_detail.pet_owner.id %}"
              >
                {{ pet_detail.pet_owner.username }}
              </a>
            </h5>
            <hr>
          </div>

        {% endif %}
        <div class="w3-container">
          {% if pet_detail.description %}
            <h5><b>Description:</b></h5>
            <h4>{{ pet_detail.description }}</h4>
          {% endif %}
          <br>
        </div>
      </div>
      {% if user.is_authenticated %}
        <div class="w3-container w3-margin-left">
          {% if pet_detail.type.name == "Dog"  %}
            <a
                href="{% url 'shelter:dog-update' pk=object.id %}"
                class="w3-btn w3-black w3-text-yellow w3-round-xxlarge"
            >
              <b>Update Info</b>
            </a>
          {% else %}
            <a
                href="{% url 'shelter:cat-update' pk=object.id %}"
                class="w3-btn w3-black w3-text-yellow w3-round-xxlarge"
            >
              <b>Update Info</b>
            </a>
          {% endif %}
        </div>
      {% endif %}
    </div>
  </div>

<script src="{% static 'js/open-adoption-form.js' %}"></script>{% endblock %}