config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shelter.urls", namespace="shelter")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

shelter/urls.py
from django.urls import path, include

from shelter.views import (
    IndexView,
    AdoptPet,
    BreedListView,
    BreedCreateView,
    BreedUpdateView,
    CatListView,
    CatCreateView,
    CatUpdateView,
    DogListView,
    DogCreateView,
    DogUpdateView,
    PetDetailView,
    PetListView,
    PetOwnerListView,
    PetOwnerCreateView,
    PetOwnerDetailView,
    PetOwnerUpdateView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "breeds/create/",
        BreedCreateView.as_view(),
        name="breed-create"
    ),
    path(
        "breeds/<int:pk>/update/",
        BreedUpdateView.as_view(),
        name="breed-update"
    ),
    path(
        "breeds/",
        BreedListView.as_view(),
        name="breed-list"
    ),
    path(
        "dogs/",
        DogListView.as_view(),
        name="dog-list"
    ),
    path(
        "dogs/create/",
        DogCreateView.as_view(),
        name="dog-create"
    ),
    path(
        "dogs/<int:pk>/update/",
        DogUpdateView.as_view(),
        name="dog-update"
    ),
    path(
        "cats/",
        CatListView.as_view(),
        name="cat-list"
    ),
    path(
        "cats/create/",
        CatCreateView.as_view(),
        name="cat-create"
    ),
    path(
        "cats/<int:pk>/update/",
        CatUpdateView.as_view(),
        name="cat-update"
    ),
    path(
        "pets/<int:pk>/detail/",
        PetDetailView.as_view(),
        name="pet-detail"
    ),
    path(
        "pets/",
        PetListView.as_view(),
        name="pet-list"
    ),
    path(
        "users/",
        PetOwnerListView.as_view(),
        name="pet-owner-list"
    ),
    path(
        "users/create/",
        PetOwnerCreateView.as_view(),
        name="pet-owner-create"
    ),
    path(
        "pets/<int:pk>/adopt/",
        AdoptPet.as_view(),
        name="adopt-pet"
    ),
    path(
        "users/<int:pk>/detail/",
        PetOwnerDetailView.as_view(),
        name="pet-owner-detail"
    ),
    path(
        "users/<int:pk>/update/",
        PetOwnerUpdateView.as_view(),
        name="pet-owner-update"
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

app_name = "shelter"

templates/includes/footer.html
{% load static %}
<div class="w3-bar w3-orange div-footer">
   <div class="w3-container">
      <p>Contact us</p>
      <p>
        petshelter@lovepets.com
        <br>
        +380 88 888 88 88
        <br>
        155 Pet Shelter Street, Kyiv, Ukraine
      </p>
   </div>

  <div class="w3-container">
    <p class="w3-center">
      Our Pet Shelter is always open for cooperation and glad for any assistance
    <div class="w3-container">
      <p class="w3-center w3-opacity">
        Copyright @2023 Pet Shelter
        <br>Site by Diana Shyrokikh
      </p>
    </div>
  </div>
</div>

templates/includes/navigation.html
{% load static %}

<div>
  <div class="w3-bar w3-black w3-round-xxlarge div-navigation">
    <div
        class="w3-bar-item w3-mobile w3-button
               w3-text-yellow w3-padding-16 w3-hover-none
               w3-hover-text-white"
    >
      <img src="{% static 'images/logo.svg' %}" alt="Logo">
    </div>

    {% if user.is_staff%}
      <a
          id="openNav"
          class="w3-bar-item w3-mobile w3-button
                 w3-text-yellow w3-padding-16 w3-hover-none
                 w3-hover-text-white w3-mobile nav-font-size-i"
          onclick="openSidebar()"
      >
        &#9776;
      </a>
    {% endif %}

    {% if not user.is_authenticated %}
      <a
          href="{% url 'shelter:login' %}"
          class="w3-bar-item w3-mobile w3-button
                 w3-text-yellow w3-padding-16 w3-right
                 w3-hover-none w3-hover-text-white"
      >
        <i class="fa fa-sign-in nav-font-size-i"></i>
      </a>

    {% else %}
        <a
            href="{% url 'shelter:logout' %}"
            class="w3-bar-item w3-mobile w3-button w3-text-yellow
                   w3-padding-16 w3-right w3-hover-none
                   w3-hover-text-white"
        >
          <i class="fa fa-sign-out nav-font-size-i"></i>
        </a>
    {% endif %}

    {% if user.is_authenticated %}
      <a
          href="{% url 'shelter:pet-owner-detail' pk=user.id %}"
          class="w3-bar-item w3-mobile w3-button w3-text-yellow
                 w3-padding-16 w3-right w3-hover-none
                 w3-hover-text-white nav-font-size"
      >
        Welcome <b>{{ user.username }}</b>
      </a>
    {% endif %}

    <a
        href="{% url 'shelter:index' %}"
        class="w3-bar-item w3-mobile w3-button w3-text-yellow
               w3-padding-16 w3-right w3-hover-none
               w3-hover-text-white"
    >
      <i class="fa fa-home nav-font-size-i"></i>
    </a>
    <a
        href="{% url 'shelter:dog-list' %}"
        id="nav-link"
        class="w3-bar-item w3-mobile w3-button w3-text-yellow
               w3-padding-16 w3-hover-none w3-hover-text-white"
    >
      Adopt a dog
    </a>
    <a
        href="{% url 'shelter:cat-list' %}"
        id="nav-link"
        class="w3-bar-item w3-mobile w3-button w3-text-yellow
               w3-padding-16 w3-hover-none w3-hover-text-white"
    >
      Adopt a cat
    </a>
  </div>
</div>

<script src="{% static 'js/open-sidebar.js' %}"></script>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="pagination w3-center w3-bar w3-margin">
    {% if page_obj.has_previous %}
      <a
          href="?{% query_transform request page=page_obj.previous_page_number%}"
          class="w3-button pag-font-size"
      >
        &laquo;
      </a>
    {% else %}
      <a href="" class="w3-button pag-font-size">&laquo;</a>
    {% endif %}

    <span class="page-link pag-font-size">
      {{ page_obj.number }} of {{ paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
      <a
          href="?{% query_transform request page=page_obj.next_page_number%}"
          class="w3-button pag-font-size"
      >
        &raquo;
      </a>
    {% else %}
      <a href="" class="w3-button pag-font-size">&raquo;</a>
    {% endif %}
  </div>
{% else %}
  <div class="pagination w3-center w3-bar w3-margin">
    <p class="pag-font-size">&nbsp;</p>
  </div>
{% endif %}

templates/includes/sidebar.html
{% load static %}

<div
    class="w3-sidebar w3-bar-block w3-round-xxlarge
           w3-center w3-text-yellow w3-black"
    id="mySidebar"
>
  <button
      class="w3-bar-item w3-button w3-large"
      onclick="closeSidebar()"
  >
    Close &times;
  </button>
  <br>
  Menu
  <br>
  <br>
  <a
      href="{% url 'shelter:breed-create' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Add Breed
  </a>
  <a
      href="{% url 'shelter:breed-list' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Breed List
  </a>
  <br>
  <a
      href="{% url 'shelter:cat-create' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Create Cat Profile
  </a>
  <a
      href="{% url 'shelter:dog-create' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Create Dog Profile
  </a>
  <a
      href="{% url 'shelter:pet-list' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Pet List
  </a>
  <br>
  <a
      href="{% url 'shelter:pet-owner-create' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    Create User Profile
  </a>
  <a
      href="{% url 'shelter:pet-owner-list' %}"
      class="w3-bar-item w3-button w3-border-bottom w3-border-yellow"
  >
    User List
  </a>
</div>

<script src="{% static 'js/close-sidebar.js' %}"></script>